#!/bin/sh

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"
shebang=$(sed -n lp "$file")

cd "$dir" || exit

texttype() {\
    command="pdflatex"
    ( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
    $command --output-directory="$dir" "$base" &&
        grep -i addbibresource "$file" > /dev/null &&
        biber --input-directory "$dir" "$base" &&
        $command --output-directory="$dir" "$base" &&
        $command --output-directory="$dir" "$base"
}

shebangtest() {
    case "$shebang" in
        \#\!*) "$file" ;;
        *) sent "$file" 2>/dev/null & ;;
    esac
}

case "$file" in
    *\.ms) groff "$file" -me -mm -ms -k -pet -Tutf-8 -mandoc -Tpdf > "$base".pdf ;;
    *\.mom) refer -PS -e "$file" | groff -mom -k -p -pet -Tutf-8 -mandoc -Tpdf > "$base".pdf ;;
    *\.md) pandoc "$file" --pdf-engine=pdflatex -o "$base".pdf --number-section ;;
    *\.tex) texttype "$file" ;;
    *\.py) python "$file" ;;
    *\.go) go run "$file" ;;
    *) shebangtest ;;
esac
