#! /bin/sh

#source $(dirname $0)/config
#source ./config/bspwm/screenlayout.sh


# xrandr --output HDMI1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output VIRTUAL1 --off --output eDP1 --mode 1366x768 --pos 1366x0 --rotate normal
sxhkd &
#megasync &
nitrogen --restore &
compton -b -c -C &
#nm-applet &
 
bspc config border_width            2
bspc config window_gap              7

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config focus_follows_pointer   true
bspc config presel_feedback_color   "#12181d"
bspc config focused_border_color "#fdf1c7"
bspc config normal_border_color "#fb4934"
bspc monitor HDMI1 -d discord terminal firefox code music matrix 
bspc monitor eDP1 -d discord terminal firefox code music matrix 


#Resize 
bspc config pointer_modifier mod4 
bspc config pointer_modifier move 
bspc config pointer_action resize_side 
bspc config pointer_action resize_corner

bspc rule -a sxiv follow=off state=floating 
bspc rule -a mpv follow=off state=floating

#panel &

$HOME/.config/polybar/launch.sh
